In [103]:
import numpy as np
import matplotlib.pyplot as plt

from anim import make_3d_animation

N_particle = 2
dim = 2
L = 10 
Nt = 10
m = 1
h = 1/(Nt)



vel = np.zeros(shape=(Nt, N_particle, dim), dtype=float)
pos = np.zeros(shape=(Nt, N_particle, dim), dtype=float)
dis = np.zeros(shape=(Nt, N_particle, dim), dtype=float)
F = np.zeros(shape=(Nt, N_particle, dim), dtype=float)

vel[0,:,:] = np.random.rand()


pos[0,0,:] = np.random.rand()
pos[0,1,:] = np.random.rand()




dis[0,0,:] = np.random.rand()
dis[0,1,:] = np.random.rand()





#dis = np.sqrt((pos[0,0,0]-pos[0,1,0])**2 + (pos[0,0,1]-pos[0,1,1])**2)

#F = -48*dis**(-13)+24*dis**(-7)


for v in range(1,Nt):
    
    dis[v] = np.sqrt((pos[v-1,0,0]-pos[v-1,1,0])**2 + (pos[v-1,0,1]-pos[v-1,1,1])**2)
    
    F[v] = -48*dis[v-1]**(-13)+24*dis[v-1]**(-7)
    print(F)
    
    vel[v,0,:] = vel[v-1,0,:]+(1/m)*h*F[v] 
       
   
    pos[v] = (pos[v-1]+h*vel[v-1]) % L
    
    
    
vsquare = np.sqrt(vel[:,0]**2+vel[:,1]**2)
psquare = np.sqrt(pos[:,0]**2+pos[:,1]**2)
x = np.linspace(1,Nt,Nt)

plt.plot(x,vsquare)
plt.show()





[[[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[ -4.36496966e+01  -4.36496966e+01]
  [ -6.32791804e+07  -6.32791804e+07]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00]]]


ValueError: could not broadcast input array from shape (2,2) into shape (2)

In [92]:
pos = np.zeros((Nt, N_particle, dim))
pos[0,0,:] = 2
pos[0,1,:] = 4


dis = np.sqrt((pos[0,0,0]-pos[0,1,0])**2 + (pos[0,0,1]-pos[0,1,1])**2)



2.82842712475
